apiVersion: v1
kind: Secret
metadata:
  name: cloudfind-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgrespassword@cloudfind-postgres-service:5432/lost_and_found"
  REDIS_URL: "redis://cloudfind-redis-service:6379/0"
  SECRET_KEY: "super-secret-k8s-jwt-key-32bytes-min!"
