"""Add moderation and verification

Revision ID: 541021547430
Revises: 
Create Date: 2026-08-16 19:30:26.411007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541021547430'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'moderationstatus') THEN 
                    CREATE TYPE moderationstatus AS ENUM ('PENDING_VERIFICATION', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'FLAGGED'); 
                END IF; 
            END $$;
        """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.Enum('LOST', 'FOUND', name='reporttype'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_email'), 'verification_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=True)
    op.add_column('found_items', sa.Column('moderation_status', sa.Enum('PENDING_VERIFICATION', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'FLAGGED', name='moderationstatus'), server_default='PENDING_VERIFICATION', nullable=False))
    op.add_column('found_items', sa.Column('text_moderation_result', sa.Text(), nullable=True))
    op.add_column('found_items', sa.Column('image_moderation_result', sa.Text(), nullable=True))
    op.add_column('found_items', sa.Column('flag_reason', sa.Text(), nullable=True))
    op.add_column('found_items', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('found_items', sa.Column('reviewed_by', sa.String(length=36), nullable=True))
    op.alter_column('found_items', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'found_items', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.add_column('lost_items', sa.Column('moderation_status', sa.Enum('PENDING_VERIFICATION', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'FLAGGED', name='moderationstatus'), server_default='PENDING_VERIFICATION', nullable=False))
    op.add_column('lost_items', sa.Column('text_moderation_result', sa.Text(), nullable=True))
    op.add_column('lost_items', sa.Column('image_moderation_result', sa.Text(), nullable=True))
    op.add_column('lost_items', sa.Column('flag_reason', sa.Text(), nullable=True))
    op.add_column('lost_items', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('lost_items', sa.Column('reviewed_by', sa.String(length=36), nullable=True))
    op.alter_column('lost_items', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'lost_items', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lost_items', type_='foreignkey')
    op.alter_column('lost_items', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('lost_items', 'reviewed_by')
    op.drop_column('lost_items', 'reviewed_at')
    op.drop_column('lost_items', 'flag_reason')
    op.drop_column('lost_items', 'image_moderation_result')
    op.drop_column('lost_items', 'text_moderation_result')
    op.drop_column('lost_items', 'moderation_status')
    op.drop_constraint(None, 'found_items', type_='foreignkey')
    op.alter_column('found_items', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('found_items', 'reviewed_by')
    op.drop_column('found_items', 'reviewed_at')
    op.drop_column('found_items', 'flag_reason')
    op.drop_column('found_items', 'image_moderation_result')
    op.drop_column('found_items', 'text_moderation_result')
    op.drop_column('found_items', 'moderation_status')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_email'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
