"""Initial migration for master spec

Revision ID: d0fda459ccd2
Revises: 
Create Date: 2026-08-17 11:30:57.760338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fda459ccd2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='ticketstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_email'), 'support_tickets', ['email'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_id'), 'support_tickets', ['ticket_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN_STAFF', 'ADMIN_OWNER', name='userrole'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.Enum('LOST', 'FOUND', name='reporttype'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_email'), 'verification_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('found_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('found_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'MATCHED', 'CLAIMED', 'RETURNED', 'CLOSED', 'HIDDEN', name='itemstatus'), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('moderated_text', sa.Text(), nullable=True),
    sa.Column('moderation_status', sa.Enum('PENDING_VERIFICATION', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'FLAGGED', name='moderationstatus'), nullable=False),
    sa.Column('image_moderation_result', sa.Text(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_items_access_token'), 'found_items', ['access_token'], unique=False)
    op.create_index(op.f('ix_found_items_location'), 'found_items', ['location'], unique=False)
    op.create_index(op.f('ix_found_items_report_id'), 'found_items', ['report_id'], unique=True)
    op.create_index(op.f('ix_found_items_verification_token'), 'found_items', ['verification_token'], unique=True)
    op.create_table('lost_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('lost_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'MATCHED', 'CLAIMED', 'RETURNED', 'CLOSED', 'HIDDEN', name='itemstatus'), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('moderated_text', sa.Text(), nullable=True),
    sa.Column('moderation_status', sa.Enum('PENDING_VERIFICATION', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'FLAGGED', name='moderationstatus'), nullable=False),
    sa.Column('image_moderation_result', sa.Text(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_items_access_token'), 'lost_items', ['access_token'], unique=False)
    op.create_index(op.f('ix_lost_items_location'), 'lost_items', ['location'], unique=False)
    op.create_index(op.f('ix_lost_items_report_id'), 'lost_items', ['report_id'], unique=True)
    op.create_index(op.f('ix_lost_items_verification_token'), 'lost_items', ['verification_token'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('staff_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_invitations_email'), 'staff_invitations', ['email'], unique=True)
    op.create_index(op.f('ix_staff_invitations_token'), 'staff_invitations', ['token'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('found_item_id', sa.String(length=36), nullable=False),
    sa.Column('claimant_id', sa.String(length=36), nullable=True),
    sa.Column('claimant_email', sa.String(length=255), nullable=True),
    sa.Column('proof_description', sa.Text(), nullable=False),
    sa.Column('verification_answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='claimstatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_item_information',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lost_item_id', sa.String(length=36), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='tipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_item_information_lost_item_id'), 'lost_item_information', ['lost_item_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lost_item_id', sa.String(length=36), nullable=False),
    sa.Column('found_item_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_index(op.f('ix_lost_item_information_lost_item_id'), table_name='lost_item_information')
    op.drop_table('lost_item_information')
    op.drop_table('claims')
    op.drop_index(op.f('ix_staff_invitations_token'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_email'), table_name='staff_invitations')
    op.drop_table('staff_invitations')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_lost_items_verification_token'), table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_report_id'), table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_location'), table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_access_token'), table_name='lost_items')
    op.drop_table('lost_items')
    op.drop_index(op.f('ix_found_items_verification_token'), table_name='found_items')
    op.drop_index(op.f('ix_found_items_report_id'), table_name='found_items')
    op.drop_index(op.f('ix_found_items_location'), table_name='found_items')
    op.drop_index(op.f('ix_found_items_access_token'), table_name='found_items')
    op.drop_table('found_items')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_email'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_support_tickets_ticket_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_email'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
